# -*- coding: utf-8 -*-
"""NeuralNetwork_AsmeetaBardiya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kdZk50vUqlVYAO1fyX5BI6u-lF7rr-nJ
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import tensorflow as tf

mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

mat

tensor = tf.convert_to_tensor(mat)

tensor

type(tensor)

a = tf.constant(5) #or u can just do like tf.covert_to_tensor(5)
a

name = tf.constant("Asmeeta Bardiya")    
name

type(name.numpy())

dir(name.numpy())

name.numpy().decode()

type(name.numpy().decode())

data = tf.keras.datasets.fashion_mnist

(x_train,y_train),(x_test,y_test) = data.load_data()

x_train.shape

class_names  = ['T-shirt/Top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']

plt.imshow(x_train[0],cmap=plt.cm.binary_r)
plt.show()

plt.figure(figsize=(20,20))
for num in range(25):
  plt.subplot(5,5,num+1)
  plt.imshow(x_train[num],cmap=plt.cm.binary_r)
  plt.xlabel(class_names[y_train[num]])
plt.show()

#Tensorflow Keras Sequential API
model = tf.keras.Sequential([
               tf.keras.layers.Flatten(input_shape=(28,28)),  
               tf.keras.layers.Dense(200,activation = 'relu'),    
               tf.keras.layers.Dense(10,activation = 'softmax')    
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy'],
)

model.summary()

model.fit(x_train,y_train,epochs=10,verbose=1)

model.evaluate(x_test,y_test,verbose=1)

model.evaluate(x_test,y_test,verbose=1)

img = x_test[10].reshape(1,28,28)

pred = np.argmax(model.predict(img))
print(pred)

plt.imshow(x_test[10],cmap=plt.cm.binary)
plt.show()

class_names[pred]

model.save('myfirstmodel.h5')